# Generated by Django 3.0.8 on 2020-07-16 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(25)])),
                ('phone_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_contact', models.EmailField(max_length=254)),
                ('is_discount_eligible', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True, verbose_name='season start date')),
                ('end_date', models.DateField(unique=True, verbose_name='season end date')),
                ('price_per_night', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField(unique=True, verbose_name='check-in date')),
                ('out_date', models.DateField(unique=True, verbose_name='check-out date')),
                ('total_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_guests', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_approved', models.BooleanField(default=False)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('additional_questions_or_concerns', models.TextField(blank=True, default='')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='registration.Guest')),
            ],
            options={
                'ordering': ['is_approved', 'in_date', 'guest'],
            },
        ),
        migrations.CreateModel(
            name='GuestNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Guest')),
            ],
        ),
    ]
