# Generated by Django 3.0.8 on 2020-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='is_using_custom_price',
            field=models.BooleanField(default=False),
        ),
    ]
