# Generated by Django 3.0.7 on 2020-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('in_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
