# Generated by Django 3.0.6 on 2020-06-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '__first__'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='corresponding_stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Stay'),
        ),
    ]
