# Generated by Django 3.0.8 on 2020-07-20 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price_per_night', models.FloatField(default=175, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_days_of_stay', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('cleaning_fee', models.FloatField(default=150, validators=[django.core.validators.MinValueValidator(0)])),
                ('state_tax_rate_percent', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('county_tax_rate_percent', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Globals',
            },
        ),
    ]
