# Generated by Django 3.0.6 on 2020-06-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price_per_night', models.FloatField(default=175)),
                ('minimum_days_of_stay', models.IntegerField(default=4)),
            ],
        ),
    ]
